[tool.poetry]
name = "humanloop-cookbook"
version = "0.1.0"
description = ""
authors = ["Peter Hayes <ucabpnh@ucl.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
